/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SignProviderService } from "../signProvider.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SignProviderCreateInput } from "./SignProviderCreateInput";
import { SignProvider } from "./SignProvider";
import { SignProviderFindManyArgs } from "./SignProviderFindManyArgs";
import { SignProviderWhereUniqueInput } from "./SignProviderWhereUniqueInput";
import { SignProviderUpdateInput } from "./SignProviderUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SignProviderControllerBase {
  constructor(
    protected readonly service: SignProviderService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SignProvider })
  @nestAccessControl.UseRoles({
    resource: "SignProvider",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSignProvider(
    @common.Body() data: SignProviderCreateInput
  ): Promise<SignProvider> {
    return await this.service.createSignProvider({
      data: data,
      select: {
        createdAt: true,
        id: true,
        name: true,
        signPrice: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [SignProvider] })
  @ApiNestedQuery(SignProviderFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SignProvider",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async signProviders(@common.Req() request: Request): Promise<SignProvider[]> {
    const args = plainToClass(SignProviderFindManyArgs, request.query);
    return this.service.signProviders({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,
        signPrice: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SignProvider })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SignProvider",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async signProvider(
    @common.Param() params: SignProviderWhereUniqueInput
  ): Promise<SignProvider | null> {
    const result = await this.service.signProvider({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,
        signPrice: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SignProvider })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SignProvider",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSignProvider(
    @common.Param() params: SignProviderWhereUniqueInput,
    @common.Body() data: SignProviderUpdateInput
  ): Promise<SignProvider | null> {
    try {
      return await this.service.updateSignProvider({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          name: true,
          signPrice: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SignProvider })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SignProvider",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSignProvider(
    @common.Param() params: SignProviderWhereUniqueInput
  ): Promise<SignProvider | null> {
    try {
      return await this.service.deleteSignProvider({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,
          signPrice: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
