/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, PaymentGateway as PrismaPaymentGateway } from "@prisma/client";
import { LocalStorageService } from "src/storage/providers/local/local.storage.service";
import { InputJsonValue } from "src/types";
import { FileDownload, FileUpload } from "src/storage/base/storage.types";
import { LocalStorageFile } from "src/storage/providers/local/local.storage.types";

export class PaymentGatewayServiceBase {
  constructor(
    protected readonly prisma: PrismaService,
    protected readonly localStorageService: LocalStorageService
  ) {}

  async count(
    args: Omit<Prisma.PaymentGatewayCountArgs, "select">
  ): Promise<number> {
    return this.prisma.paymentGateway.count(args);
  }

  async paymentGateways(
    args: Prisma.PaymentGatewayFindManyArgs
  ): Promise<PrismaPaymentGateway[]> {
    return this.prisma.paymentGateway.findMany(args);
  }
  async paymentGateway(
    args: Prisma.PaymentGatewayFindUniqueArgs
  ): Promise<PrismaPaymentGateway | null> {
    return this.prisma.paymentGateway.findUnique(args);
  }
  async createPaymentGateway(
    args: Prisma.PaymentGatewayCreateArgs
  ): Promise<PrismaPaymentGateway> {
    return this.prisma.paymentGateway.create(args);
  }
  async updatePaymentGateway(
    args: Prisma.PaymentGatewayUpdateArgs
  ): Promise<PrismaPaymentGateway> {
    return this.prisma.paymentGateway.update(args);
  }
  async deletePaymentGateway(
    args: Prisma.PaymentGatewayDeleteArgs
  ): Promise<PrismaPaymentGateway> {
    return this.prisma.paymentGateway.delete(args);
  }

  async uploadLogo<T extends Prisma.PaymentGatewayFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.PaymentGatewayFindUniqueArgs>,
    file: FileUpload
  ): Promise<PrismaPaymentGateway> {
    file.filename = `profilePicture-${args.where.id}.${file.filename
      .split(".")
      .pop()}`;
    const containerPath = "/payment_gateways/";
    const logo = await this.localStorageService.uploadFile(
      file,
      [],
      1000000,
      containerPath
    );

    return await this.prisma.paymentGateway.update({
      where: args.where,

      data: {
        logo: logo as InputJsonValue,
      },
    });
  }

  async downloadLogo<T extends Prisma.PaymentGatewayFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.PaymentGatewayFindUniqueArgs>
  ): Promise<FileDownload> {
    const { logo } = await this.prisma.paymentGateway.findUniqueOrThrow({
      where: args.where,
    });

    return await this.localStorageService.downloadFile(
      logo as unknown as LocalStorageFile
    );
  }

  async deleteLogo<T extends Prisma.PaymentGatewayFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.PaymentGatewayFindUniqueArgs>
  ): Promise<PrismaPaymentGateway> {
    const { logo } = await this.prisma.paymentGateway.findUniqueOrThrow({
      where: args.where,
    });

    await this.localStorageService.deleteFile(
      logo as unknown as LocalStorageFile
    );

    return await this.prisma.paymentGateway.update({
      where: args.where,

      data: {
        logo: Prisma.DbNull,
      },
    });
  }
}
